name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Install eslint
      run: yarn global eslint add
    - name: Lint
      run: eslint \"src/**/*.js\" \"src/**/*.jsx\" --fix
